---
abstract: 'The great new CHI::Driver::DBIC!'
author:
  - 'Motortrak Ltd <duncan.garland@motortrak.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CHI-Driver-DBIC
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.008
version: 0.001_001
